version: '3.7'
services:
  lb:
    image: 'openresty/openresty:buster-fat'
    volumes:
      - ./lb/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./lb/nginx/conf.d:/etc/nginx/conf.d
      - ./lb/dlb:/usr/local/openresty/dlb
    ports:
      - 8888:80
    networks:
      internal:
        ipv4_address: 172.28.0.100
        aliases:
          - lb
  backend1:
    image: 'openresty/openresty:buster-fat'
    volumes:
      - ./backend1/nginx/conf.d:/etc/nginx/conf.d
    networks:
      internal:
        ipv4_address: 172.28.0.101
        aliases:
          - backend1
  backend2:
    image: 'openresty/openresty:buster-fat'
    volumes:
      - ./backend2/nginx/conf.d:/etc/nginx/conf.d
    networks:
      internal:
        ipv4_address: 172.28.0.102
        aliases:
          - backend2
  backend3:
    image: 'openresty/openresty:buster-fat'
    volumes:
      - ./backend3/nginx/conf.d:/etc/nginx/conf.d
    networks:
      internal:
        ipv4_address: 172.28.0.103
        aliases:
          - backend3

networks:
  internal:
    ipam:
      config:
        - subnet: 172.28.0.0/16
